### PR TITLE
Feature/scala3 2nd

### PR DESCRIPTION
**Pull request by pityka**

### CODE REVIEW

**Comment by pityka** [comment]
@tnielens following your changes this branch is now green. I did not want to force push the other PR branch.

[2126964](https://github.com/pityka/saddle/pull/440/commits/212696466826f799897211a0df43e24cfb9eb8b1) worth having a look, it is not the nicest solution.

Also 3.1.2 fails to compile the ScalarGen tests. I am not sure what is the problem with type inference there. I am ok to merge with 3.1.1

**Comment by tnielens** [comment]
> Also 3.1.2 fails to compile the ScalarGen tests. I am not sure what is the problem with type inference there. I am ok to merge with 3.1.1

I filed a bug in the scala issue tracker https://github.com/lampepfl/dotty/issues/15178 a few days ago. It should be solved in 3.1.3. I should have mentioned this earlier to save you some time. Sorry for that.

**Comment by tnielens** [comment]
> [2126964](https://github.com/pityka/saddle/pull/440/commits/212696466826f799897211a0df43e24cfb9eb8b1) worth having a look, it is not the nicest solution.

Yeah gave it a try, but bumped into an sbt macro error, as you surely did too. Not sure how to clean that up. 
How can the project linalg depend on the inlined ops with scala2 and not with scala3?

**Comment by tnielens** [comment]
About the duplication of test files `VecArbitraries.scala`, `MatArbitraries.scala` and `framework.scala` in `saddle-ops-inlined/src/test`, if you change `.dependsOn(coreJVM, inlinedOpsMacroImpl % "compile->compile;test->test")` by `.dependsOn(coreJVM % "compile->compile;test->test", inlinedOpsMacroImpl)`, the duplication can be reverted.

**Review by pityka — COMMENTED** [review]
@tnielens 

I reviewed this again. with the exception of the duplicated test code this is ok for me. I will eliminate that duplication as you suggested.

Let me know if you want to review this again.

**Comment by tnielens** [comment]
My two remaining remarks are above, one about the duplication of tests and 

> Yeah gave it a try, but bumped into an sbt macro error, as you surely did too. Not sure how to clean that up.
I tried without the linalg -> inlinedOps. Seems to work fine. Could we remove that dependency?

Second comment, if applied, would remove the sbt project definition hack.

**Comment by pityka** [comment]
We can't remove the dependency because it was a dependency in the last release on scala2 thus mima complains. client code might expect it to be there.

**Comment by pityka** [comment]
@tnielens that linalg3 submodule indeed had to be removed. with this only the core module is on scala3. separate PRs can address the rest. 

Thank you for the help!

**Pull request merged**
