### PR TITLE
add fillNA on Frame

### PR DESCRIPTION
**Pull request by tnielens**

### CODE REVIEW

**Comment by pityka** [comment]
CI came back with the following issues. I think the first we can ignore, the rest is neither clear for me because VecImpl is private[saddle].

```
[error]  * abstract method fillNA(org.saddle.package#FillMethod,Int)org.saddle.Vec in interface org.saddle.Vec is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("org.saddle.Vec.fillNA")
[error]  * interface org.saddle.vec.VecImpl#Fill does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("org.saddle.vec.VecImpl$Fill")
[error]  * object org.saddle.vec.VecImpl#Fill does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("org.saddle.vec.VecImpl$Fill$")
[error]  * object org.saddle.vec.VecImpl#Fill#Backward does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("org.saddle.vec.VecImpl$Fill$Backward$")
[error]  * object org.saddle.vec.VecImpl#Fill#Forward does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("org.saddle.vec.VecImpl$Fill$Forward$")
```

**Comment by tnielens** [comment]
The new method `Vec.fillNA` causes an incompatibility because it's abstract and the implementation is in `VecDefault`.
This was the case as well when `Vec.fillForward/Backward` was added. Adding an abstract/unimplemented method to a trait is a binary incompat because the user could extend it without an implementation for the new method. That said, `Vec` has abstract private methods like 
```scala
  private[saddle] def toDoubleArray(implicit na: NUM[T]): Array[Double]
 ```
 which prevents user extensions. So I think we can ignore it.
 
 As for the errors in `VecImpl`, that object is private so we can ignore that as well.

**Comment by pityka** [comment]
OK. Could you add the respective mima ignore lines to the build.sbt ? Thank you!

**Comment by tnielens** [comment]
Was 3.1.1 published on maven central? My local attempts at running mima fail due not found previous artifacts.

**Comment by pityka** [comment]
3.1.1 release did not end up at maven (none of the artifacts). I don't exactly know why.
Probably it was a bit premature to make the release so I took the opportunity and deleted my local and the remote tag.

**Comment by pityka** [comment]
@tnielens do you see CI logs? In case not, the 2.12 build fails with this:

Frame.scala:38:19: imported `FillMethod` is permanently hidden by definition of class FillMethod in package saddle
[error] import org.saddle.FillMethod

**Pull request merged**
