### PR TITLE
scala3 - further reverts, drop collection compat, merge master

### PR DESCRIPTION
**Pull request by tnielens**
- further reverts, ~~try to preserve BinaryCompat~~
- merge master
- drop collection-compat, unnecessary if saddle doesn't cross compile 2.12.

Easier to review if target branch is master and not pityka/feature/scala3

EDIT: given the list of binary incompatibility errors, I'm giving up on it this time.

### CODE REVIEW

**Comment by pityka** [comment]
can you help me what is the difference between this and pityka/feature/scala3 ?

**Comment by tnielens** [comment]
> can you help me what is the difference between this and pityka/feature/scala3 ?

- remove the `scalarTag` field from `ScalarTag`
- remove the collection.compat dependency
- a couple of small reverts (reintroducing a removed method) that were introduced in pityka/feature/scala3, but seemed unrelated. Maybe you took the opportunity to remove some methods since you were making a binary breaking change?
- merging master

If you merge master in pityka/feature/scala3, this diff should be more palatable.

**Comment by pityka** [comment]
I went commit by commit:
[105a870](https://github.com/pityka/saddle/pull/425/commits/105a87013011b4cc58986c23e13b43e20cd1a300) is OK for me
[0e178ab](https://github.com/pityka/saddle/pull/425/commits/0e178ab367ca74d87c54d6c1bb0cbb2d6668e042) also OK

What remains is to decide what to do with the long mima list.

**Comment by tnielens** [comment]
> I went commit by commit: [105a870](https://github.com/pityka/saddle/pull/425/commits/105a87013011b4cc58986c23e13b43e20cd1a300) is OK for me [0e178ab](https://github.com/pityka/saddle/pull/425/commits/0e178ab367ca74d87c54d6c1bb0cbb2d6668e042) also OK
> 
> What remains is to decide what to do with the long mima list.

Yes nothing more than these commits. A lot of this are reverts from your PR. What about cherry picking this over to your PR and squashing everything into a single commit? That'd avoid unnecessary git annotations on code changed-reverted.
You can squash my commits, I don't care about the authorship on those.

**Comment by tnielens** [comment]
Closing as commits were incorporated in #388.

**Pull request closed without merging**
